### ISSUE TITLE
ooyala api returns 400 invalid signature on POST

### ISSUE THREAD

**Issue by patprzybilla** [brightcove-archive/ooyala_node-ooyala-api-client#1]
Hey there

I am trying to create assets using the wrapper but I cant pass the signature challange.

{ api_key: '15Y3E6NbxVLo2xTPCDLwz2ud2_Aj.pgWiH',
  expires: 1359546916910,
  signature: 'I2X/+bFJ95hZiX6VNUwjBwsGdfpydAJdtQaYTMxWtmQ=' }
{ host: 'api.ooyala.com',
  port: '80',
  path: '/v2/assets?api_key=15Y3E6NbxVLo2xTPCDLwz2ud2_Aj.pgWiH&expires=1359546916910&signature=I2X%2F%2BbFJ95hZiX6VNUwjBwsGdfpydAJdtQaYTMxWtmQ%3D',
  headers: 
   { 'Content-length': 113,
     HTTP_X_API_KEY: '15Y3E6NbxVLo2xTPCDLwz2ud2_Aj.pgWiH',
     'X-API-KEY': '15Y3E6NbxVLo2xTPCDLwz2ud2_Aj.pgWiH' },
  method: 'POST' }
400 '{"status":"400 Bad Request","content-type":"application/json","ooyala-server-id":"i-38e3a140","ooyala-request-id":"60f4a8b1ec8489d17e5639a585ae9038","content-length":"32","accept-ranges":"bytes","date":"Wed, 30 Jan 2013 12:00:00 GMT","x-varnish":"2156404367","age":"0","via":"1.1 varnish","connection":"close","x-varnish-cache":"MISS"}'
Body is {"message":"Invalid signature."}

**Comment by patprzybilla** [comment]
line 43 in client.js

change:

params["signature"] = this._sign(params, method, apiPath, body)

to:

params["signature"] = this._sign(params, method, apiPath, body).slice(0,43);

**Comment by ruiyang2012** [comment]
thanks, fixed in 0e1497ab7b3dd660f3970daaa76213ed6c1291b7
