### ISSUE TITLE
Adding PATCH to the client.

### ISSUE THREAD

**Issue by patprzybilla** [brightcove-archive/ooyala_node-ooyala-api-client#3]
Its less an issue but more an improvement. I ve tested PATCH and PUT request to push metadata and being able to update the assets via the client and it seems to work.

so at line 21 - 35 I ve got and its working as expected. Could you commit it so we dont have to patch the module?

OO._.extend(OoyalaApiClient.prototype, {
  post: function(headers, apiPath, params, body, statusCb, dataCb, errCb, context) {
    this._curl('POST', headers, apiPath, params, body, statusCb, dataCb, errCb, context);
  },

  put: function(headers, apiPath, params, body, statusCb, dataCb, errCb, context) {
    this._curl('PUT', headers, apiPath, params, body, statusCb, dataCb, errCb, context);
  },

  get: function(headers, apiPath, params, statusCb, dataCb, errCb, context) {
    this._curl('GET', headers, apiPath, params, null, statusCb, dataCb, errCb, context)
  },
  patch: function(headers, apiPath, params, body, statusCb, dataCb, errCb, context) {
    this._curl('PATCH', headers, apiPath, params, body, statusCb, dataCb, errCb, context)
  },

**Comment by patprzybilla** [comment]
duplicate due pull request

**Comment by Karima22** [comment]
Hi there, I've been using this module in my API and am having some issues with the PATCH request.
After I issue a PATCH request on a given asset, the edited property of the asset appears as it should on the Backlot UI, but when I issue a following GET request using the new property value in the query parameters, Ooyala returns an empty items array (i.e. it can't find any matching assets). 
If I use the old property value (the value before patching) I then receive the asset in the response from Ooyala. 
It takes a very long time (maybe 15 minutes) for the query with the new property value to work and return the patched asset and for the query with the old property value to return an empty items array.
